samples: config/samples.tsv
experiments: config/experiments.csv
pipeline_base: /storage/zhangyanxiaoLab/qihongjian/projects/paired_seq_tag/data/xx_pipeline
merge_base: /storage/zhangyanxiaoLab/qihongjian/projects/paired_seq_tag/data/merge
